### ISSUE TITLE
microblaze lvgl

### ISSUE THREAD

**Issue by IZBH** [MaxwellWjj/Zynq_LCD_LittleVGL#1]
看到您的readme当中有用microblaze实现lvgl，麻烦问您开源吗？可以的话想借鉴以下代码

**Comment by MaxwellWjj** [comment]
您好！我的朋友之前已经将其开源，我是借鉴他的microblaze版本移植的
Here is the link:
https://github.com/OliverPai/Microblaze-littlevGL

**Comment by IZBH** [comment]
嗯嗯，谢谢您
